version: '3'

services:
  solr:
    build:
      context: ./compose/solr
      #dockerfile: ./compose/solr/Dockerfile
    image: nomenmatch-solr:8
    restart: always
    ports:
      - "8990:8990"
    volumes:
      - solr-data:/var/solr/data
      - ./solr-workspace:/workspace
      - ../nm-volumes/solr:/var/solr
    command:
      - solr-precreate
      #- gettingstarted
  nginx:
    image: nginx:latest
    ports:
        - "81:81"
    volumes:
        - ./:/code
        - ./compose/nginx-tbia:/etc/nginx/conf.d
  php:
    image: php:7-fpm
    # ports:
    #   - 9000:9000
    volumes:
        - ./:/code
        - ./source-data:/code/source-data

volumes:
  solr-data: